apiVersion: v1
kind: Service
metadata:
  labels:
    name: tb
  name: tb
  namespace: default
spec:
  ports:
  - name: postgres
    nodePort: 30383
    port: 5432
    protocol: TCP
    targetPort: 5432
  - name: ui
    nodePort: 32472
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: mqtt
    nodePort: 31972
    port: 2883
    protocol: TCP
    targetPort: 2883
  - name: coap
    nodePort: 30806
    port: 5683
    protocol: TCP
    targetPort: 5683
  - name: rpc
    nodePort: 31978
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    run: tb
  sessionAffinity: None
  type: LoadBalancer

